### ISSUE TITLE
New format for requirement

### ISSUE THREAD

**Issue by HSGamer** [BetterGUI-MC/BetterGUI#13]
Format:
```yaml
<any_name>:
  type: <requirement_type>
  value: <value>
  take: <true/false>
  command:
  - command1
  - command2
  ...
```
