### ISSUE TITLE
Replace the format of requirements (allow multiple sets of requirements)

### ISSUE THREAD

**Issue by HSGamer** [BetterGUI-MC/BetterGUI#15]
The format:
```yaml
# click-requirement:
view-requirement:
  <name1>:
    <requirement1>: <value1>
    <requirement2>: <value2>
    <requirement3>:
      value: <value3>
      take: <true/false>
    ...
    success-command:
    - command1
    - command2
  <name2>:
    <requirement1>: <value1>
    <requirement2>: <value2>
    <requirement3>:
      value: <value3>
      take: <true/false>
    ...
    success-command:
    - command1
    - command2
  fail-command:
  - command1
  - command2
...
```
This is an example of the new format of requirements:
```yaml
click-requirement:
  money-permission:
    condition: "{money} > 100"
    permission: "test.money.permission"
    success-command:
    - "tell: &aAlright! You are in"
  level-permission:
    level:
      value: 10
      take: true
    permission: "test.level.permission"
    success-command:
    - "tell: &aAlright! You are in"
  level-max:
    level: 10
    success-command:
    - "tell: &cYou can get it for free"
  fail-command:
  - "tell: &cNo. Try again"
```
