### ISSUE TITLE
Inventory close not work in Minecraft 1.17 version

### ISSUE THREAD

**Issue by andris155** [BetterGUI-MC/BetterGUI#217]
### **Describe the bug**
* [x] Make sure you've read the wiki

### **To Reproduce**
1. Install the plugin.
2. Create a menu item with close-on-click: true.
3. Click to the menu item.
4. The menu close not work.

### **Expected behavior**

close-on-click: true item close the inventory in Minecraft 1.17 version.

### **Details**
```
kilepes:
  ID: barrier
  LORE:
    - '&7Klikk a kilépéshez!'
  POSITION-X: 6
  NAME: '&4Kilépés a menüből'
  POSITION-Y: 6
  close-on-click: true
```

### **Version**
- Minecraft: 1.17
- Spigot/Bukkit/...: Paper
- BetterGUI: 6.0-SNAPSHOT
- Installed Addons: BungeeLink
