### ISSUE TITLE
Animation frames are not processed in the correct order

### ISSUE THREAD

**Issue by lokka30** [BetterGUI-MC/BetterGUI#252]
Note: This issue uses Minecraft 1.19 which is not a supported version. #251

***

### Describe the bug

[x] Make sure you've read the wiki

The following animation does not appear in the correct order (descending):

```yaml
default-icon:
  type: animated
  child:
    frame_icon1:
      ID: gray stained glass pane
      NAME: '&aH&7ello'
    frame_icon2:
      ID: gray stained glass pane
      NAME: '&7H&ae&7llo'
    frame_icon3:
      ID: gray stained glass pane
      NAME: '&7He&al&7lo'
    frame_icon4:
      ID: gray stained glass pane
      NAME: '&7Hel&al&7o'
    frame_icon5:
      ID: gray stained glass pane
      NAME: '&7Hell&ao'
    frame_icon6:
      ID: gray stained glass pane
      NAME: '&7Hello'
    frame_icon7:
      ID: gray stained glass pane
      NAME: '&aHello'
    frame_icon8:
      ID: gray stained glass pane
      NAME: '&7Hello'
```

This default icon is used in the standard 'example' menu with no other changes.

### **To Reproduce**
1. Declare an animated button
...

### **Expected behavior**

Animation frames are processed from top to bottom, which can be reversed using `reverse`.

### **Screenshots**

I unfortunately don't have recording software to show it on my screen - if you can't reproduce it, I'll gladly try find something that works.

### **Details**

Full file: [example.yml](https://paste.gg/p/anonymous/3c8d6aa72b504fbdb751df3207238772)

### **Version**
- Minecraft 1.19 client and server
- BetterGUI: v6.6
- Installed Addons: None

### **Additional context**

Running Paper-81 MC 1.19.
